// <auto-generated />
using System;
using DisputePortal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisputePortal.Persistence.Migrations
{
    [DbContext(typeof(DisputePortalDbContext))]
    partial class DisputePortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisputePortal.Application.Domain.Enums.AccountTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccountType", "Data");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Savings Account",
                            Name = "Savings"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cheque Account",
                            Name = "Cheque"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Current Account",
                            Name = "Current"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Credit Account",
                            Name = "Credit"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Business Account",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fixed Deposit Account",
                            Name = "FixedDeposit"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Investment Account",
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Loan Account",
                            Name = "Loan"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Joint Account",
                            Name = "Joint"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Foreign Currency Account",
                            Name = "ForeignCurrency"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Student Account",
                            Name = "Student"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Retirement Account",
                            Name = "Retirement"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Money Market Account",
                            Name = "MoneyMarket"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Islamic Banking Account",
                            Name = "Islamic"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Trust Account",
                            Name = "Trust"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Digital Wallet Account",
                            Name = "DigitalWallet"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Corporate Account",
                            Name = "Corporate"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Offshore Account",
                            Name = "Offshore"
                        });
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Enums.DisputeReasonCodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DisputeReasonCode", "Static");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Unauthorised Transaction",
                            Name = "UnauthorisedTransaction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Incorrect Transaction Amount",
                            Name = "IncorrectAmount"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Duplicate Charge",
                            Name = "DuplicateCharge"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Merchant Dispute",
                            Name = "MerchantDispute"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Card Not Present Fraud",
                            Name = "CardNotPresentFraud"
                        },
                        new
                        {
                            Id = 6,
                            Description = "ATM Cash Not Dispensed",
                            Name = "AtmCashNotDispensed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "ATM Partial Cash Dispensed",
                            Name = "AtmPartialCashDispensed"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Transaction Reversed but Funds Not Returned",
                            Name = "ReversalNotProcessed"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cash Withdrawal Not Authorised",
                            Name = "UnauthorizedWithdrawal"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Subscription Cancellation Dispute",
                            Name = "SubscriptionCancelled"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Goods or Services Not Received",
                            Name = "GoodsNotReceived"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Defective or Damaged Goods",
                            Name = "DefectiveGoods"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Refund Not Processed",
                            Name = "RefundNotProcessed"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Incorrect Merchant Charged",
                            Name = "IncorrectMerchant"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Transaction Processed Multiple Times",
                            Name = "MultipleProcessing"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Fraudulent Online Transaction",
                            Name = "OnlineFraud"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Identity Theft Suspected",
                            Name = "IdentityTheft"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Card Stolen or Lost",
                            Name = "LostOrStolenCard"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Service Not As Described",
                            Name = "ServiceNotAsDescribed"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Charge After Cancellation",
                            Name = "ChargeAfterCancellation"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Late Presentment",
                            Name = "LatePresentment"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Incorrect Currency Conversion",
                            Name = "IncorrectCurrencyConversion"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Account Credited Incorrectly",
                            Name = "IncorrectCredit"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Dispute Already Resolved",
                            Name = "AlreadyResolved"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Other Dispute Reason",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Enums.DisputeStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DisputeStatus", "Static");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Submitted",
                            Name = "Submitted"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Under Review",
                            Name = "UnderReview"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Resolved",
                            Name = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rejected",
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Enums.TransactionCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransactionCategory", "Static");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Money Transfer",
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Purchase",
                            Name = "Purchase"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cash Withdrawal",
                            Name = "Withdrawal"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Account Deposit",
                            Name = "Deposit"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Service Fee",
                            Name = "Fee"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bill Payment",
                            Name = "BillPayment"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Refund",
                            Name = "Refund"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Salary Payment",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Interest Earned",
                            Name = "Interest"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Loan Repayment",
                            Name = "LoanRepayment"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Mobile Recharge",
                            Name = "Airtime"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Insurance Payment",
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Tax Payment",
                            Name = "Tax"
                        },
                        new
                        {
                            Id = 14,
                            Description = "ATM Fee",
                            Name = "AtmFee"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Card Payment",
                            Name = "CardPayment"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cheque Deposit",
                            Name = "ChequeDeposit"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Reversal Transaction",
                            Name = "Reversal"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Subscription Payment",
                            Name = "Subscription"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Investment Contribution",
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Other Transaction",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.AppUserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUser", "Security");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.BankAccountModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ZAR");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BankAccount", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.CustomerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customer", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.DisputeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisputeReasonId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisputeReasonId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("CustomerId", "StatusId");

                    b.ToTable("Dispute", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.DisputeStatusHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedByRole")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("DisputeId", "ChangedAt");

                    b.ToTable("DisputeStatusHistory", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DisputeId");

                    b.ToTable("Notification", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.RefreshTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshToken", "Security");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.TransactionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("boolean");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId", "TransactionDate");

                    b.ToTable("Transaction", "Data");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.BankAccountModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Enums.AccountTypeModel", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Models.CustomerModel", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.DisputeModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Models.CustomerModel", "Customer")
                        .WithMany("Disputes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Enums.DisputeReasonCodeModel", "DisputeReason")
                        .WithMany()
                        .HasForeignKey("DisputeReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Enums.DisputeStatusModel", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Models.TransactionModel", "Transaction")
                        .WithOne("Dispute")
                        .HasForeignKey("DisputePortal.Application.Domain.Models.DisputeModel", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DisputeReason");

                    b.Navigation("Status");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.DisputeStatusHistoryModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Models.DisputeModel", "Dispute")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Enums.DisputeStatusModel", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Enums.DisputeStatusModel", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispute");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.NotificationModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Models.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Models.DisputeModel", "Dispute")
                        .WithMany("Notifications")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.RefreshTokenModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Models.AppUserModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.TransactionModel", b =>
                {
                    b.HasOne("DisputePortal.Application.Domain.Models.BankAccountModel", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisputePortal.Application.Domain.Models.CustomerModel", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.AppUserModel", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.BankAccountModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.CustomerModel", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Disputes");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.DisputeModel", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("DisputePortal.Application.Domain.Models.TransactionModel", b =>
                {
                    b.Navigation("Dispute");
                });
#pragma warning restore 612, 618
        }
    }
}
